fileimport:
    mode: transport
    root: json
    index: typophile
    type: article
    
    max_bulk_actions: 1000
    max_concurrent_bulk_requests: 1
    max_volume_per_bulk_request: 10mb
    
    # needed when mode: transport
    transport:
        addresses:
            - localhost:9300
